[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=node_modules/@openzeppelin/', 'forge-std/=lib/forge-std/src']
fuzz_runs = 256
gas_reports = ["*"]
eth-rpc-url = 'https://mainnet.infura.io/v3/9ccb2a35e7f64383ac06acbbe33e1a29'
solc_version = '0.8.10'

# See more config options https://github.com/gakonst/foundry/tree/master/config
